; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = arduino
platform_packages = platformio/tool-openocd@2.1100.211028

lib_deps =
    https://github.com/adafruit/adafruit_vl53l0x
